name: peval
description: "Pe-val.ro POS Application"
publish_to: 'none'

version: 1.0.1+18

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  isar: ^3.1.0+1
  path_provider: ^2.1.2
  intl: ^0.19.0  # Pentru formatarea datelor și a valutei
  isar_flutter_libs: ^3.1.0+1  # Adăugat biblioteca nativă pentru Isar
  esc_pos_utils: 
    git:
      url: https://github.com/ES-fooshen/esc_pos_utils.git
      ref: master

dependency_overrides:
  intl: ^0.19.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  go_router_builder: ^2.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
 
